export const ExtensionMessageType = {
  WORKSPACEUPDATED: 0,
  SET_APP_MODE: 1,
  FILE_OPENED: 2,
  FILE_SAVE_RESULT: 3,

  // Database responses
  DB_DATABASES_LISTED: 100,
  DB_CONNECTIONS_LISTED: 101,
  DB_CONNECTION_SAVED: 102,
  DB_CONNECTION_TESTED: 103,
  DB_CONNECTED: 104,
  DB_DISCONNECTED: 105,
  DB_QUERY_RESULT: 106,
  DB_SCHEMA: 107,
  DB_ERROR: 108,
  DB_CONNECTION_CONFIG: 109,
  DB_CONNECTION_DELETED: 110,
  DB_CONNECTION_UPDATED: 111,
  DB_PROJECTS_LISTED: 112,
  DB_PROJECT_CREATED: 113,
  DB_PROJECT_DELETED: 114,
  DB_PROJECT_UPDATED: 115,
  DB_PROJECT_ASSIGNED: 116,
  DB_CLOUD_ACCOUNTS_LISTED: 117,
  DB_CLOUD_ACCOUNT_CREATED: 118,
  DB_CLOUD_ACCOUNT_DELETED: 119,
  EDITOR_LOAD_TYPES: 120,
} as const;

export type ExtensionMessageType = (typeof ExtensionMessageType)[keyof typeof ExtensionMessageType];