export const WebviewMessageType = {
  OPEN_EDITOR: "OPEN_EDITOR",
  WEBVIEW_DID_LAUNCH: "WEBVIEW_DID_LAUNCH",
  REQUEST_OPEN_FILE: "REQUEST_OPEN_FILE",
  REQUEST_SAVE_FILE: "REQUEST_SAVE_FILE",

  // Database operations
  DB_LIST_DATABASES: "DB_LIST_DATABASES",
  DB_GET_CONNECTIONS: "DB_GET_CONNECTIONS",
  DB_SAVE_CONNECTION: "DB_SAVE_CONNECTION",
  DB_TEST_CONNECTION: "DB_TEST_CONNECTION",
  DB_CONNECT: "DB_CONNECT",
  DB_DISCONNECT: "DB_DISCONNECT",
  DB_EXECUTE_QUERY: "DB_EXECUTE_QUERY",
  DB_GET_SCHEMA: "DB_GET_SCHEMA",
  DB_GET_CONNECTION_CONFIG: "DB_GET_CONNECTION_CONFIG",
  DB_DELETE_CONNECTION: "DB_DELETE_CONNECTION",
  DB_UPDATE_CONNECTION: "DB_UPDATE_CONNECTION",
  DB_LIST_PROJECTS: "DB_LIST_PROJECTS",
  DB_CREATE_PROJECT: "DB_CREATE_PROJECT",
  DB_UPDATE_PROJECT: "DB_UPDATE_PROJECT",
  DB_DELETE_PROJECT: "DB_DELETE_PROJECT",
  DB_ASSIGN_CONNECTION_TO_PROJECT: "DB_ASSIGN_CONNECTION_TO_PROJECT",
  DB_COPY_CONNECTION: "DB_COPY_CONNECTION",
} as const;

export type WebViewMessageType = (typeof WebviewMessageType)[keyof typeof WebviewMessageType];