export const WebviewMessageType = {
  OPEN_EDITOR: "OPEN_EDITOR",
  WEBVIEW_DID_LAUNCH: "WEBVIEW_DID_LAUNCH",
  REQUEST_OPEN_FILE: "REQUEST_OPEN_FILE",
  REQUEST_SAVE_FILE: "REQUEST_SAVE_FILE",

  // Database operations
  DB_LIST_DATABASES: "DB_LIST_DATABASES",
  DB_GET_CONNECTIONS: "DB_GET_CONNECTIONS",
  DB_SAVE_CONNECTION: "DB_SAVE_CONNECTION",
  DB_TEST_CONNECTION: "DB_TEST_CONNECTION",
  DB_CONNECT: "DB_CONNECT",
  DB_DISCONNECT: "DB_DISCONNECT",
  DB_EXECUTE_QUERY: "DB_EXECUTE_QUERY",
  DB_GET_SCHEMA: "DB_GET_SCHEMA",
  DB_GET_CONNECTION_CONFIG: "DB_GET_CONNECTION_CONFIG",
} as const;

export type WebViewMessageType = (typeof WebviewMessageType)[keyof typeof WebviewMessageType];