import { DatabaseDefinition, DatabaseCategory, ConnectionMethod, QueryLanguage } from "../types/database-definition";
import { ConnectionFieldType } from "../types/connection-config";

/**
 * Common connection fields reused across many databases.
 */
const hostField = {
  key: "host",
  label: "Host",
  type: ConnectionFieldType.TEXT,
  required: true,
  placeholder: "localhost",
  group: "Connection",
} as const;

const portField = {
  key: "port",
  label: "Port",
  type: ConnectionFieldType.NUMBER,
  placeholder: "5432",
  group: "Connection",
} as const;

const databaseField = {
  key: "database",
  label: "Database",
  type: ConnectionFieldType.TEXT,
  placeholder: "mydb",
  group: "Connection",
} as const;

const usernameField = {
  key: "username",
  label: "Username",
  type: ConnectionFieldType.TEXT,
  placeholder: "admin",
  group: "Authentication",
} as const;

const passwordField = {
  key: "password",
  label: "Password",
  type: ConnectionFieldType.PASSWORD,
  sensitive: true,
  group: "Authentication",
  helpText: "Password will be saved in Visual Studio Code's secret storage facility.",
} as const;

const sslField = {
  key: "ssl",
  label: "Use SSL",
  type: ConnectionFieldType.CHECKBOX,
  defaultValue: false,
  group: "Connection",
} as const;

const connectionStringField = {
  key: "connectionString",
  label: "Connection String",
  type: ConnectionFieldType.TEXTAREA,
  placeholder: "postgresql://user:pass@host:5432/db",
  group: "Connection",
  helpText: "Paste a full connection string. This will override individual fields.",
} as const;

const roleField = {
  key: "role",
  label: "Role",
  type: ConnectionFieldType.SELECT,
  options: [
    { label: "None", value: "none" },
    { label: "Development", value: "development" },
    { label: "Testing", value: "testing" },
    { label: "Production", value: "production" },
  ],
  defaultValue: "none",
  group: "Authentication",
  helpText: "Role permissions can be configured in settings.",
} as const;

const postConnectionSqlField = {
  key: "postConnectionSqlSource",
  label: "Post-Connection SQL Source",
  type: ConnectionFieldType.SELECT,
  options: [
    { label: "Inline Script", value: "inline" },
    { label: "File", value: "file" },
  ],
  defaultValue: "inline",
  group: "Advanced",
  helpText: "Runs immediately after the connection opens. Choose whether to write SQL inline or use a file.",
} as const;

const postConnectionSqlInlineField = {
  key: "postConnectionSql",
  label: "SQL Script",
  type: ConnectionFieldType.TEXTAREA,
  group: "Advanced",
  dependsOn: { field: "postConnectionSqlSource", value: "inline" },
} as const;

const postConnectionSqlFileField = {
  key: "postConnectionSqlFile",
  label: "SQL Script File",
  type: ConnectionFieldType.FILE,
  group: "Advanced",
  dependsOn: { field: "postConnectionSqlSource", value: "file" },
} as const;

const progressiveLoadingField = {
  key: "progressiveLoading",
  label: "Progressive Loading",
  type: ConnectionFieldType.CHECKBOX,
  defaultValue: true,
  group: "Advanced",
  helpText: "Load schema details on-demand for faster initial connection.",
} as const;

const prefetchDetailsField = {
  key: "prefetchDetails",
  label: "Prefetch Details",
  type: ConnectionFieldType.CHECKBOX,
  defaultValue: false,
  group: "Advanced",
  helpText: "Fetch full schema details in the background after connecting.",
} as const;

const batchSizeField = {
  key: "batchSize",
  label: "Batch Size",
  type: ConnectionFieldType.NUMBER,
  defaultValue: 10,
  group: "Advanced",
} as const;

const cacheTtlField = {
  key: "cacheTtlDays",
  label: "Cache TTL",
  type: ConnectionFieldType.NUMBER,
  defaultValue: 7,
  group: "Advanced",
} as const;

const storeInWorkspaceField = {
  key: "storeInWorkspace",
  label: "Store in workspace",
  type: ConnectionFieldType.CHECKBOX,
  defaultValue: false,
  group: "General",
  helpText: "Saved in the .code-workspace or .vscode/settings.json file, enabling sharing via Git.",
} as const;

const commonAdvancedFields = [
  postConnectionSqlField,
  postConnectionSqlInlineField,
  postConnectionSqlFileField,
  progressiveLoadingField,
  prefetchDetailsField,
  batchSizeField,
  cacheTtlField,
  storeInWorkspaceField,
];

/**
 * All supported database definitions.
 */
export const DATABASE_DEFINITIONS: DatabaseDefinition[] = [
  // ==================== SQL DATABASES ====================
  {
    id: "postgresql",
    name: "PostgreSQL",
    category: DatabaseCategory.SQL,
    connectionMethod: ConnectionMethod.NATIVE,
    queryLanguage: QueryLanguage.SQL,
    driverPackage: "pg",
    driverTypesPackage: "@types/pg",
    description: "Open-source relational database system",
    defaultPort: 5432,
    fields: [
      hostField,
      { ...portField, defaultValue: 5432 },
      databaseField,
      usernameField,
      passwordField,
      sslField,
      connectionStringField,
      roleField,
      ...commonAdvancedFields,
    ],
  },
  {
    id: "mysql",
    name: "MySQL",
    category: DatabaseCategory.SQL,
    connectionMethod: ConnectionMethod.NATIVE,
    queryLanguage: QueryLanguage.SQL,
    driverPackage: "mysql2",
    description: "Popular open-source relational database",
    defaultPort: 3306,
    fields: [
      hostField,
      { ...portField, defaultValue: 3306 },
      databaseField,
      usernameField,
      passwordField,
      sslField,
      connectionStringField,
      roleField,
      ...commonAdvancedFields,
    ],
  },
  {
    id: "sqlite",
    name: "SQLite",
    category: DatabaseCategory.SQL,
    connectionMethod: ConnectionMethod.NATIVE,
    queryLanguage: QueryLanguage.SQL,
    driverPackage: "better-sqlite3",
    driverTypesPackage: "@types/better-sqlite3",
    description: "Embedded SQL database engine",
    fields: [
      {
        key: "filePath",
        label: "Database File",
        type: ConnectionFieldType.FILE,
        required: true,
        group: "Connection",
        helpText: "Path to the .db/.sqlite file",
      },
      connectionStringField,
      roleField,
      ...commonAdvancedFields,
    ],
  },
  {
    id: "sqlserver",
    name: "SQL Server",
    category: DatabaseCategory.SQL,
    connectionMethod: ConnectionMethod.NATIVE,
    queryLanguage: QueryLanguage.SQL,
    driverPackage: "mssql",
    description: "Microsoft's enterprise relational database",
    defaultPort: 1433,
    fields: [
      hostField,
      { ...portField, defaultValue: 1433 },
      databaseField,
      usernameField,
      passwordField,
      sslField,
      connectionStringField,
      roleField,
      ...commonAdvancedFields,
    ],
  },
  {
    id: "mongodb",
    name: "MongoDB",
    category: DatabaseCategory.NOSQL,
    connectionMethod: ConnectionMethod.NATIVE,
    queryLanguage: QueryLanguage.MQL,
    driverPackage: "mongodb",
    description: "Document-oriented NoSQL database",
    defaultPort: 27017,
    fields: [
      hostField,
      { ...portField, defaultValue: 27017 },
      databaseField,
      usernameField,
      passwordField,
      sslField,
      connectionStringField,
      roleField,
      ...commonAdvancedFields,
    ],
  },
  {
    id: "redis",
    name: "Redis",
    category: DatabaseCategory.NOSQL,
    connectionMethod: ConnectionMethod.NATIVE,
    queryLanguage: QueryLanguage.REDIS,
    driverPackage: "ioredis",
    description: "In-memory data structure store",
    defaultPort: 6379,
    fields: [
      hostField,
      { ...portField, defaultValue: 6379 },
      {
        key: "database",
        label: "Database Index",
        type: ConnectionFieldType.NUMBER,
        defaultValue: 0,
        group: "Connection",
      },
      usernameField,
      passwordField,
      sslField,
      connectionStringField,
      roleField,
      ...commonAdvancedFields,
    ],
  },
  {
    id: "mariadb",
    name: "MariaDB",
    category: DatabaseCategory.SQL,
    connectionMethod: ConnectionMethod.NATIVE,
    queryLanguage: QueryLanguage.SQL,
    driverPackage: "mariadb",
    description: "MySQL-compatible relational database",
    defaultPort: 3306,
    fields: [
      hostField,
      { ...portField, defaultValue: 3306 },
      databaseField,
      usernameField,
      passwordField,
      sslField,
      connectionStringField,
      roleField,
      ...commonAdvancedFields,
    ],
  },
  {
    id: "duckdb",
    name: "DuckDB",
    category: DatabaseCategory.SQL,
    connectionMethod: ConnectionMethod.NATIVE,
    queryLanguage: QueryLanguage.SQL,
    driverPackage: "duckdb",
    description: "In-process analytical database",
    fields: [
      {
        key: "filePath",
        label: "Database File",
        type: ConnectionFieldType.FILE,
        group: "Connection",
        helpText: "Leave empty for in-memory database",
      },
      connectionStringField,
      roleField,
      ...commonAdvancedFields,
    ],
  },
  {
    id: "oracle",
    name: "Oracle",
    category: DatabaseCategory.SQL,
    connectionMethod: ConnectionMethod.NATIVE,
    queryLanguage: QueryLanguage.SQL,
    driverPackage: "oracledb",
    description: "Enterprise relational database",
    defaultPort: 1521,
    fields: [
      hostField,
      { ...portField, defaultValue: 1521 },
      {
        key: "database",
        label: "Service Name / SID",
        type: ConnectionFieldType.TEXT,
        placeholder: "ORCL",
        group: "Connection",
      },
      usernameField,
      passwordField,
      sslField,
      connectionStringField,
      roleField,
      ...commonAdvancedFields,
    ],
  },
  {
    id: "clickhouse",
    name: "ClickHouse",
    category: DatabaseCategory.SQL,
    connectionMethod: ConnectionMethod.HTTP,
    queryLanguage: QueryLanguage.SQL,
    driverPackage: "@clickhouse/client",
    description: "Column-oriented OLAP database",
    defaultPort: 8123,
    fields: [
      hostField,
      { ...portField, defaultValue: 8123 },
      databaseField,
      usernameField,
      passwordField,
      sslField,
      connectionStringField,
      roleField,
      ...commonAdvancedFields,
    ],
  },
  {
    id: "apache-derby",
    name: "Apache Derby",
    category: DatabaseCategory.SQL,
    connectionMethod: ConnectionMethod.NATIVE,
    queryLanguage: QueryLanguage.SQL,
    driverPackage: "node-jdbc",
    description: "Java-based relational database",
    defaultPort: 1527,
    fields: [
      {
        key: "connectionMode",
        label: "Connection Mode",
        type: ConnectionFieldType.SELECT,
        options: [
          { label: "Directory", value: "directory" },
          { label: "Server", value: "server" },
          { label: "In-Memory", value: "memory" },
        ],
        defaultValue: "directory",
        required: true,
        group: "Connection",
      },
      {
        key: "filePath",
        label: "Directory",
        type: ConnectionFieldType.FILE,
        group: "Connection",
        dependsOn: { field: "connectionMode", value: "directory" },
      },
      hostField,
      { ...portField, defaultValue: 1527 },
      databaseField,
      usernameField,
      passwordField,
      roleField,
      {
        key: "createIfNotExists",
        label: "Create if not exists",
        type: ConnectionFieldType.CHECKBOX,
        defaultValue: false,
        group: "Advanced",
        helpText: "Append `;create=true` to the JDBC URL so Derby creates the database on first connect.",
      },
      ...commonAdvancedFields,
    ],
  },
  {
    id: "dameng",
    name: "Dameng",
    category: DatabaseCategory.SQL,
    connectionMethod: ConnectionMethod.NATIVE,
    queryLanguage: QueryLanguage.SQL,
    driverPackage: "dm-jdbc",
    description: "Chinese enterprise relational database",
    defaultPort: 5236,
    preview: true,
    fields: [
      hostField,
      { ...portField, defaultValue: 5236 },
      databaseField,
      usernameField,
      passwordField,
      sslField,
      connectionStringField,
      roleField,
      ...commonAdvancedFields,
    ],
  },
  {
    id: "exasol",
    name: "Exasol",
    category: DatabaseCategory.SQL,
    connectionMethod: ConnectionMethod.NATIVE,
    queryLanguage: QueryLanguage.SQL,
    driverPackage: "exasol-driver",
    description: "High-performance analytics database",
    defaultPort: 8563,
    fields: [
      hostField,
      { ...portField, defaultValue: 8563 },
      databaseField,
      usernameField,
      passwordField,
      sslField,
      connectionStringField,
      roleField,
      ...commonAdvancedFields,
    ],
  },
  {
    id: "firebird",
    name: "Firebird",
    category: DatabaseCategory.SQL,
    connectionMethod: ConnectionMethod.NATIVE,
    queryLanguage: QueryLanguage.SQL,
    driverPackage: "node-firebird",
    description: "Open-source relational database",
    defaultPort: 3050,
    preview: true,
    fields: [
      hostField,
      { ...portField, defaultValue: 3050 },
      databaseField,
      usernameField,
      passwordField,
      sslField,
      connectionStringField,
      roleField,
      ...commonAdvancedFields,
    ],
  },
  {
    id: "greenplum",
    name: "Greenplum",
    category: DatabaseCategory.SQL,
    connectionMethod: ConnectionMethod.NATIVE,
    queryLanguage: QueryLanguage.SQL,
    driverPackage: "pg",
    description: "PostgreSQL-based MPP database",
    defaultPort: 5432,
    fields: [
      hostField,
      { ...portField, defaultValue: 5432 },
      databaseField,
      usernameField,
      passwordField,
      sslField,
      connectionStringField,
      roleField,
      ...commonAdvancedFields,
    ],
  },
  {
    id: "h2",
    name: "H2 Database",
    category: DatabaseCategory.SQL,
    connectionMethod: ConnectionMethod.NATIVE,
    queryLanguage: QueryLanguage.SQL,
    driverPackage: "node-jdbc",
    description: "Java SQL database",
    defaultPort: 9092,
    fields: [
      {
        key: "connectionMode",
        label: "Connection Mode",
        type: ConnectionFieldType.SELECT,
        options: [
          { label: "Embedded", value: "embedded" },
          { label: "Server", value: "server" },
          { label: "In-Memory", value: "memory" },
        ],
        defaultValue: "embedded",
        group: "Connection",
      },
      {
        key: "filePath",
        label: "Database File",
        type: ConnectionFieldType.FILE,
        group: "Connection",
        dependsOn: { field: "connectionMode", value: "embedded" },
      },
      hostField,
      { ...portField, defaultValue: 9092 },
      databaseField,
      usernameField,
      passwordField,
      roleField,
      ...commonAdvancedFields,
    ],
  },
  {
    id: "ibm-db2",
    name: "IBM DB2",
    category: DatabaseCategory.SQL,
    connectionMethod: ConnectionMethod.NATIVE,
    queryLanguage: QueryLanguage.SQL,
    driverPackage: "ibm_db",
    description: "IBM enterprise relational database",
    defaultPort: 50000,
    fields: [
      hostField,
      { ...portField, defaultValue: 50000 },
      databaseField,
      usernameField,
      passwordField,
      sslField,
      connectionStringField,
      roleField,
      ...commonAdvancedFields,
    ],
  },
  {
    id: "ibm-i",
    name: "IBM i",
    category: DatabaseCategory.SQL,
    connectionMethod: ConnectionMethod.NATIVE,
    queryLanguage: QueryLanguage.SQL,
    driverPackage: "odbc",
    description: "IBM i (AS/400) database",
    defaultPort: 446,
    preview: true,
    fields: [
      hostField,
      { ...portField, defaultValue: 446 },
      databaseField,
      usernameField,
      passwordField,
      sslField,
      connectionStringField,
      roleField,
      ...commonAdvancedFields,
    ],
  },
  {
    id: "influxdb",
    name: "InfluxDB",
    category: DatabaseCategory.NOSQL,
    connectionMethod: ConnectionMethod.HTTP,
    queryLanguage: QueryLanguage.INFLUXQL,
    driverPackage: "@influxdata/influxdb-client",
    description: "Time-series database",
    defaultPort: 8086,
    fields: [
      hostField,
      { ...portField, defaultValue: 8086 },
      {
        key: "database",
        label: "Bucket / Database",
        type: ConnectionFieldType.TEXT,
        group: "Connection",
      },
      {
        key: "token",
        label: "API Token",
        type: ConnectionFieldType.PASSWORD,
        sensitive: true,
        group: "Authentication",
      },
      usernameField,
      passwordField,
      sslField,
      connectionStringField,
      roleField,
      ...commonAdvancedFields,
    ],
  },
  {
    id: "kingbasees",
    name: "KingbaseES",
    category: DatabaseCategory.SQL,
    connectionMethod: ConnectionMethod.NATIVE,
    queryLanguage: QueryLanguage.SQL,
    driverPackage: "pg",
    description: "Chinese PostgreSQL-compatible database",
    defaultPort: 54321,
    fields: [
      hostField,
      { ...portField, defaultValue: 54321 },
      databaseField,
      usernameField,
      passwordField,
      sslField,
      connectionStringField,
      roleField,
      ...commonAdvancedFields,
    ],
  },
  {
    id: "libsql",
    name: "libSQL",
    category: DatabaseCategory.SQL,
    connectionMethod: ConnectionMethod.NATIVE,
    queryLanguage: QueryLanguage.SQL,
    driverPackage: "@libsql/client",
    description: "Open-source SQLite-compatible database",
    fields: [
      {
        key: "filePath",
        label: "Database File",
        type: ConnectionFieldType.FILE,
        group: "Connection",
      },
      {
        key: "url",
        label: "libSQL URL",
        type: ConnectionFieldType.URL,
        placeholder: "libsql://your-db.turso.io",
        group: "Connection",
      },
      {
        key: "authToken",
        label: "Auth Token",
        type: ConnectionFieldType.PASSWORD,
        sensitive: true,
        group: "Authentication",
      },
      connectionStringField,
      roleField,
      ...commonAdvancedFields,
    ],
  },
  {
    id: "ms-access",
    name: "Microsoft Access",
    category: DatabaseCategory.SQL,
    connectionMethod: ConnectionMethod.ODBC,
    queryLanguage: QueryLanguage.SQL,
    driverPackage: "odbc",
    description: "Microsoft desktop database",
    fields: [
      {
        key: "filePath",
        label: "Access Database File",
        type: ConnectionFieldType.FILE,
        required: true,
        group: "Connection",
        helpText: "Path to .accdb or .mdb file",
      },
      usernameField,
      passwordField,
      roleField,
      ...commonAdvancedFields,
    ],
  },
  {
    id: "netezza",
    name: "Netezza",
    category: DatabaseCategory.SQL,
    connectionMethod: ConnectionMethod.NATIVE,
    queryLanguage: QueryLanguage.SQL,
    driverPackage: "pg",
    description: "IBM analytics warehouse",
    defaultPort: 5480,
    fields: [
      hostField,
      { ...portField, defaultValue: 5480 },
      databaseField,
      usernameField,
      passwordField,
      sslField,
      connectionStringField,
      roleField,
      ...commonAdvancedFields,
    ],
  },
  {
    id: "pglite",
    name: "PGlite",
    category: DatabaseCategory.SQL,
    connectionMethod: ConnectionMethod.NATIVE,
    queryLanguage: QueryLanguage.SQL,
    driverPackage: "@electric-sql/pglite",
    description: "PostgreSQL compiled to WebAssembly",
    preview: true,
    fields: [
      {
        key: "filePath",
        label: "Database File",
        type: ConnectionFieldType.FILE,
        group: "Connection",
        helpText: "Leave empty for in-memory database",
      },
      roleField,
      ...commonAdvancedFields,
    ],
  },
  {
    id: "questdb",
    name: "QuestDB",
    category: DatabaseCategory.SQL,
    connectionMethod: ConnectionMethod.NATIVE,
    queryLanguage: QueryLanguage.SQL,
    driverPackage: "pg",
    description: "High-performance time-series database",
    defaultPort: 8812,
    fields: [
      hostField,
      { ...portField, defaultValue: 8812 },
      databaseField,
      usernameField,
      passwordField,
      sslField,
      connectionStringField,
      roleField,
      ...commonAdvancedFields,
    ],
  },
  {
    id: "sap-ase",
    name: "SAP ASE (Sybase)",
    category: DatabaseCategory.SQL,
    connectionMethod: ConnectionMethod.NATIVE,
    queryLanguage: QueryLanguage.SQL,
    driverPackage: "tedious",
    description: "SAP Adaptive Server Enterprise",
    defaultPort: 5000,
    fields: [
      hostField,
      { ...portField, defaultValue: 5000 },
      databaseField,
      usernameField,
      passwordField,
      sslField,
      connectionStringField,
      roleField,
      ...commonAdvancedFields,
    ],
  },
  {
    id: "sap-hana",
    name: "SAP HANA",
    category: DatabaseCategory.SQL,
    connectionMethod: ConnectionMethod.NATIVE,
    queryLanguage: QueryLanguage.SQL,
    driverPackage: "@sap/hana-client",
    description: "SAP in-memory database",
    defaultPort: 30015,
    preview: true,
    fields: [
      hostField,
      { ...portField, defaultValue: 30015 },
      databaseField,
      usernameField,
      passwordField,
      sslField,
      connectionStringField,
      roleField,
      ...commonAdvancedFields,
    ],
  },
  {
    id: "starrocks",
    name: "StarRocks",
    category: DatabaseCategory.SQL,
    connectionMethod: ConnectionMethod.NATIVE,
    queryLanguage: QueryLanguage.SQL,
    driverPackage: "mysql2",
    description: "Analytical MPP database",
    defaultPort: 9030,
    fields: [
      hostField,
      { ...portField, defaultValue: 9030 },
      databaseField,
      usernameField,
      passwordField,
      sslField,
      connectionStringField,
      roleField,
      ...commonAdvancedFields,
    ],
  },
  {
    id: "teradata",
    name: "Teradata",
    category: DatabaseCategory.SQL,
    connectionMethod: ConnectionMethod.NATIVE,
    queryLanguage: QueryLanguage.SQL,
    driverPackage: "teradata-nodejs-driver",
    description: "Enterprise analytics database",
    defaultPort: 1025,
    preview: true,
    fields: [
      hostField,
      { ...portField, defaultValue: 1025 },
      databaseField,
      usernameField,
      passwordField,
      sslField,
      connectionStringField,
      roleField,
      ...commonAdvancedFields,
    ],
  },
  {
    id: "tidb",
    name: "TiDB",
    category: DatabaseCategory.SQL,
    connectionMethod: ConnectionMethod.NATIVE,
    queryLanguage: QueryLanguage.SQL,
    driverPackage: "mysql2",
    description: "MySQL-compatible distributed database",
    defaultPort: 4000,
    fields: [
      hostField,
      { ...portField, defaultValue: 4000 },
      databaseField,
      usernameField,
      passwordField,
      sslField,
      connectionStringField,
      roleField,
      ...commonAdvancedFields,
    ],
  },
  {
    id: "vertica",
    name: "Vertica",
    category: DatabaseCategory.SQL,
    connectionMethod: ConnectionMethod.NATIVE,
    queryLanguage: QueryLanguage.SQL,
    driverPackage: "vertica-nodejs",
    description: "Analytics columnar database",
    defaultPort: 5433,
    preview: true,
    fields: [
      hostField,
      { ...portField, defaultValue: 5433 },
      databaseField,
      usernameField,
      passwordField,
      sslField,
      connectionStringField,
      roleField,
      ...commonAdvancedFields,
    ],
  },
];

/**
 * Get a database definition by its id.
 */
export function getDatabaseDefinition(id: string): DatabaseDefinition | undefined {
  return DATABASE_DEFINITIONS.find((db) => db.id === id);
}

/**
 * Get all database definitions grouped by category.
 */
export function getDatabasesByCategory(): Record<string, DatabaseDefinition[]> {
  const grouped: Record<string, DatabaseDefinition[]> = {};
  for (const db of DATABASE_DEFINITIONS) {
    if (!grouped[db.category]) {
      grouped[db.category] = [];
    }
    grouped[db.category].push(db);
  }
  return grouped;
}