import { DatabaseCategory, ConnectionMethod, QueryLanguage } from "../types/database-definition";
import type { DatabaseDefinition } from "../types/database-definition";
import { ConnectionFieldType } from "../types/connection-config";

/**
 * Reusable field helpers for extended databases.
 */
const hostField = {
  key: "host",
  label: "Host",
  type: ConnectionFieldType.TEXT,
  required: true,
  placeholder: "localhost",
  group: "Connection",
} as const;

const portField = {
  key: "port",
  label: "Port",
  type: ConnectionFieldType.NUMBER,
  placeholder: "0000",
  group: "Connection",
} as const;

const databaseField = {
  key: "database",
  label: "Database",
  type: ConnectionFieldType.TEXT,
  placeholder: "mydb",
  group: "Connection",
} as const;

const usernameField = {
  key: "username",
  label: "Username",
  type: ConnectionFieldType.TEXT,
  placeholder: "admin",
  group: "Authentication",
} as const;

const passwordField = {
  key: "password",
  label: "Password",
  type: ConnectionFieldType.PASSWORD,
  sensitive: true,
  group: "Authentication",
  helpText: "Password will be saved in Visual Studio Code's secret storage facility.",
} as const;

const sslField = {
  key: "ssl",
  label: "Use SSL",
  type: ConnectionFieldType.CHECKBOX,
  defaultValue: false,
  group: "Connection",
} as const;

const connectionStringField = {
  key: "connectionString",
  label: "Connection String",
  type: ConnectionFieldType.TEXTAREA,
  placeholder: "mongodb://user:pass@host:27017/db",
  group: "Connection",
  helpText: "Paste a full connection string. This will override individual fields.",
} as const;

const tokenField = {
  key: "apiToken",
  label: "API Token",
  type: ConnectionFieldType.PASSWORD,
  sensitive: true,
  group: "Authentication",
} as const;

const regionField = {
  key: "region",
  label: "Region",
  type: ConnectionFieldType.TEXT,
  placeholder: "us-east-1",
  group: "Connection",
} as const;

const accessKeyField = {
  key: "accessKeyId",
  label: "Access Key ID",
  type: ConnectionFieldType.TEXT,
  group: "Authentication",
} as const;

const secretKeyField = {
  key: "secretAccessKey",
  label: "Secret Access Key",
  type: ConnectionFieldType.PASSWORD,
  sensitive: true,
  group: "Authentication",
} as const;

const commonAdvanced = [
  {
    key: "progressiveLoading",
    label: "Progressive Loading",
    type: ConnectionFieldType.CHECKBOX,
    defaultValue: true,
    group: "Advanced",
  },
  {
    key: "prefetchDetails",
    label: "Prefetch Details",
    type: ConnectionFieldType.CHECKBOX,
    defaultValue: false,
    group: "Advanced",
  },
  {
    key: "storeInWorkspace",
    label: "Store in workspace",
    type: ConnectionFieldType.CHECKBOX,
    defaultValue: false,
    group: "General",
  },
] as const;

/**
 * Extended database definitions for NoSQL, Warehouses, Cloud, and more.
 */
export const EXTENDED_DATABASE_DEFINITIONS: DatabaseDefinition[] = [
  // ==================== NoSQL DATABASES ====================
  {
    id: "aerospike",
    name: "Aerospike",
    category: DatabaseCategory.NOSQL,
    connectionMethod: ConnectionMethod.NATIVE,
    queryLanguage: QueryLanguage.SQL,
    driverPackage: "aerospike",
    description: "High-performance NoSQL database",
    defaultPort: 3000,
    fields: [hostField, { ...portField, defaultValue: 3000 }, sslField, connectionStringField],
  },
  {
    id: "amazon-documentdb",
    name: "Amazon DocumentDB",
    category: DatabaseCategory.NOSQL,
    connectionMethod: ConnectionMethod.NATIVE,
    queryLanguage: QueryLanguage.MQL,
    driverPackage: "mongodb",
    description: "MongoDB-compatible document database",
    defaultPort: 27017,
    fields: [hostField, { ...portField, defaultValue: 27017 }, databaseField, usernameField, passwordField, sslField, connectionStringField, ...commonAdvanced],
  },
  {
    id: "couchdb",
    name: "Apache CouchDB",
    category: DatabaseCategory.NOSQL,
    connectionMethod: ConnectionMethod.HTTP,
    queryLanguage: QueryLanguage.REST,
    driverPackage: "nano",
    description: "JSON document database with REST API",
    defaultPort: 5984,
    fields: [hostField, { ...portField, defaultValue: 5984 }, usernameField, passwordField, sslField, connectionStringField],
  },
  {
    id: "cassandra",
    name: "Cassandra",
    category: DatabaseCategory.NOSQL,
    connectionMethod: ConnectionMethod.NATIVE,
    queryLanguage: QueryLanguage.CQL,
    driverPackage: "cassandra-driver",
    description: "Wide-column distributed database",
    defaultPort: 9042,
    fields: [
      hostField,
      { ...portField, defaultValue: 9042 },
      databaseField,
      usernameField,
      passwordField,
      sslField,
      connectionStringField,
      ...commonAdvanced,
    ],
  },
  {
    id: "couchbase",
    name: "Couchbase",
    category: DatabaseCategory.NOSQL,
    connectionMethod: ConnectionMethod.NATIVE,
    queryLanguage: QueryLanguage.SQL,
    driverPackage: "couchbase",
    description: "Distributed NoSQL document database",
    defaultPort: 8091,
    fields: [hostField, { ...portField, defaultValue: 8091 }, usernameField, passwordField, sslField, connectionStringField],
  },
  {
    id: "dynamodb",
    name: "DynamoDB",
    category: DatabaseCategory.NOSQL,
    connectionMethod: ConnectionMethod.AWS_SDK,
    queryLanguage: QueryLanguage.REST,
    driverPackage: "@aws-sdk/client-dynamodb",
    description: "AWS managed NoSQL database",
    fields: [regionField, accessKeyField, secretKeyField, ...commonAdvanced],
  },
  {
    id: "elasticsearch",
    name: "Elasticsearch",
    category: DatabaseCategory.NOSQL,
    connectionMethod: ConnectionMethod.HTTP,
    queryLanguage: QueryLanguage.ELASTICSEARCH_DSL,
    driverPackage: "@elastic/elasticsearch",
    description: "Distributed search and analytics engine",
    defaultPort: 9200,
    fields: [hostField, { ...portField, defaultValue: 9200 }, usernameField, passwordField, sslField, connectionStringField, ...commonAdvanced],
  },
  {
    id: "firebase",
    name: "Firebase",
    category: DatabaseCategory.NOSQL,
    connectionMethod: ConnectionMethod.HTTP,
    queryLanguage: QueryLanguage.REST,
    driverPackage: "firebase-admin",
    description: "Google mobile/web app platform",
    fields: [
      { key: "projectId", label: "Project ID", type: ConnectionFieldType.TEXT, required: true, group: "Connection" },
      { key: "serviceAccountJson", label: "Service Account JSON", type: ConnectionFieldType.JSON, group: "Authentication", helpText: "Paste the Firebase service account key JSON" },
      { key: "databaseUrl", label: "Database URL", type: ConnectionFieldType.URL, placeholder: "https://your-app.firebaseio.com", group: "Connection" },
      ...commonAdvanced,
    ],
  },
  {
    id: "memcached",
    name: "Memcached",
    category: DatabaseCategory.NOSQL,
    connectionMethod: ConnectionMethod.NATIVE,
    queryLanguage: QueryLanguage.MEMCACHED,
    driverPackage: "memcached",
    description: "Distributed memory object caching",
    defaultPort: 11211,
    fields: [hostField, { ...portField, defaultValue: 11211 }, usernameField, passwordField, sslField, connectionStringField],
  },
  {
    id: "opensearch",
    name: "OpenSearch",
    category: DatabaseCategory.NOSQL,
    connectionMethod: ConnectionMethod.HTTP,
    queryLanguage: QueryLanguage.ELASTICSEARCH_DSL,
    driverPackage: "@opensearch-project/opensearch",
    description: "Open-source search and analytics",
    defaultPort: 9200,
    fields: [hostField, { ...portField, defaultValue: 9200 }, usernameField, passwordField, sslField, connectionStringField, ...commonAdvanced],
  },
  {
    id: "ravendb",
    name: "RavenDB",
    category: DatabaseCategory.NOSQL,
    connectionMethod: ConnectionMethod.NATIVE,
    queryLanguage: QueryLanguage.REST,
    driverPackage: "ravendb",
    description: "Document database for .NET",
    defaultPort: 8080,
    fields: [hostField, { ...portField, defaultValue: 8080 }, databaseField, usernameField, passwordField, sslField, connectionStringField],
  },
  {
    id: "scylladb",
    name: "ScyllaDB",
    category: DatabaseCategory.NOSQL,
    connectionMethod: ConnectionMethod.NATIVE,
    queryLanguage: QueryLanguage.CQL,
    driverPackage: "cassandra-driver",
    description: "Low-latency wide-column database",
    defaultPort: 9042,
    preview: true,
    fields: [hostField, { ...portField, defaultValue: 9042 }, databaseField, usernameField, passwordField, sslField, connectionStringField, ...commonAdvanced],
  },
  {
    id: "surreal-db",
    name: "SurrealDB",
    category: DatabaseCategory.NOSQL,
    connectionMethod: ConnectionMethod.NATIVE,
    queryLanguage: QueryLanguage.SQL,
    driverPackage: "surrealdb",
    description: "Multi-model database",
    defaultPort: 8000,
    fields: [hostField, { ...portField, defaultValue: 8000 }, databaseField, usernameField, passwordField, sslField, connectionStringField],
  },
  {
    id: "typedb",
    name: "TypeDB",
    category: DatabaseCategory.NOSQL,
    connectionMethod: ConnectionMethod.NATIVE,
    queryLanguage: QueryLanguage.CYPHER,
    driverPackage: "typedb-driver",
    description: "Strongly-typed graph database",
    defaultPort: 1729,
    fields: [hostField, { ...portField, defaultValue: 1729 }, databaseField, usernameField, passwordField, sslField, connectionStringField],
  },
  {
    id: "valkey",
    name: "Valkey",
    category: DatabaseCategory.NOSQL,
    connectionMethod: ConnectionMethod.NATIVE,
    queryLanguage: QueryLanguage.REDIS,
    driverPackage: "ioredis",
    description: "Open-source in-memory data store (Redis fork)",
    defaultPort: 6379,
    fields: [hostField, { ...portField, defaultValue: 6379 }, databaseField, usernameField, passwordField, sslField, connectionStringField],
  },

  // ==================== DATA WAREHOUSES ====================
  {
    id: "apache-doris",
    name: "Apache Doris",
    category: DatabaseCategory.DATA_WAREHOUSE,
    connectionMethod: ConnectionMethod.NATIVE,
    queryLanguage: QueryLanguage.SQL,
    driverPackage: "mysql2",
    description: "Real-time analytical database",
    defaultPort: 9030,
    fields: [hostField, { ...portField, defaultValue: 9030 }, databaseField, usernameField, passwordField, sslField, connectionStringField, ...commonAdvanced],
  },
  {
    id: "apache-druid",
    name: "Apache Druid",
    category: DatabaseCategory.DATA_WAREHOUSE,
    connectionMethod: ConnectionMethod.HTTP,
    queryLanguage: QueryLanguage.SQL,
    driverPackage: "node-druid-query",
    description: "Real-time analytics database",
    defaultPort: 8888,
    fields: [hostField, { ...portField, defaultValue: 8888 }, usernameField, passwordField, sslField, connectionStringField],
  },
  {
    id: "apache-hive",
    name: "Apache Hive",
    category: DatabaseCategory.DATA_WAREHOUSE,
    connectionMethod: ConnectionMethod.NATIVE,
    queryLanguage: QueryLanguage.SQL,
    driverPackage: "hive-driver",
    description: "Data warehouse for Hadoop",
    defaultPort: 10000,
    fields: [hostField, { ...portField, defaultValue: 10000 }, databaseField, usernameField, passwordField, sslField, connectionStringField, ...commonAdvanced],
  },
  {
    id: "apache-impala",
    name: "Apache Impala",
    category: DatabaseCategory.DATA_WAREHOUSE,
    connectionMethod: ConnectionMethod.NATIVE,
    queryLanguage: QueryLanguage.SQL,
    driverPackage: "impala",
    description: "MPP SQL engine for Hadoop",
    defaultPort: 21050,
    fields: [hostField, { ...portField, defaultValue: 21050 }, databaseField, usernameField, passwordField, sslField, connectionStringField],
  },
  {
    id: "apache-pinot",
    name: "Apache Pinot",
    category: DatabaseCategory.DATA_WAREHOUSE,
    connectionMethod: ConnectionMethod.HTTP,
    queryLanguage: QueryLanguage.SQL,
    driverPackage: "pinot-client",
    description: "Real-time OLAP database",
    defaultPort: 8099,
    preview: true,
    fields: [hostField, { ...portField, defaultValue: 8099 }, usernameField, passwordField, sslField, connectionStringField],
  },
  {
    id: "athena",
    name: "Athena",
    category: DatabaseCategory.DATA_WAREHOUSE,
    connectionMethod: ConnectionMethod.AWS_SDK,
    queryLanguage: QueryLanguage.SQL,
    driverPackage: "@aws-sdk/client-athena",
    description: "AWS serverless query service",
    fields: [regionField, accessKeyField, secretKeyField, { key: "s3OutputLocation", label: "S3 Output Location", type: ConnectionFieldType.TEXT, placeholder: "s3://bucket/prefix/", group: "Connection" }, ...commonAdvanced],
  },
  {
    id: "bigquery",
    name: "BigQuery",
    category: DatabaseCategory.DATA_WAREHOUSE,
    connectionMethod: ConnectionMethod.NATIVE,
    queryLanguage: QueryLanguage.SQL,
    driverPackage: "@google-cloud/bigquery",
    description: "Google serverless data warehouse",
    fields: [
      { key: "projectId", label: "Project ID", type: ConnectionFieldType.TEXT, required: true, group: "Connection" },
      { key: "serviceAccountJson", label: "Service Account JSON", type: ConnectionFieldType.JSON, group: "Authentication", helpText: "Paste the Google service account key JSON" },
      ...commonAdvanced,
    ],
  },
  {
    id: "databricks",
    name: "Databricks",
    category: DatabaseCategory.DATA_WAREHOUSE,
    connectionMethod: ConnectionMethod.HTTP,
    queryLanguage: QueryLanguage.SQL,
    driverPackage: "@databricks/sql",
    description: "Unified data analytics platform",
    fields: [
      { key: "serverHostname", label: "Server Hostname", type: ConnectionFieldType.TEXT, required: true, placeholder: "adb-xxx.cloud.databricks.com", group: "Connection" },
      { key: "httpPath", label: "HTTP Path", type: ConnectionFieldType.TEXT, required: true, placeholder: "/sql/1.0/warehouses/xxx", group: "Connection" },
      tokenField,
      ...commonAdvanced,
    ],
  },
  {
    id: "microsoft-fabric",
    name: "Microsoft Fabric",
    category: DatabaseCategory.DATA_WAREHOUSE,
    connectionMethod: ConnectionMethod.NATIVE,
    queryLanguage: QueryLanguage.SQL,
    driverPackage: "mssql",
    description: "Microsoft unified analytics platform",
    defaultPort: 1433,
    fields: [hostField, { ...portField, defaultValue: 1433 }, databaseField, usernameField, passwordField, sslField, connectionStringField, ...commonAdvanced],
  },
  {
    id: "redshift",
    name: "Redshift",
    category: DatabaseCategory.DATA_WAREHOUSE,
    connectionMethod: ConnectionMethod.NATIVE,
    queryLanguage: QueryLanguage.SQL,
    driverPackage: "pg",
    description: "AWS petabyte-scale data warehouse",
    defaultPort: 5439,
    fields: [hostField, { ...portField, defaultValue: 5439 }, databaseField, usernameField, passwordField, sslField, connectionStringField, ...commonAdvanced],
  },
  {
    id: "snowflake",
    name: "Snowflake",
    category: DatabaseCategory.DATA_WAREHOUSE,
    connectionMethod: ConnectionMethod.NATIVE,
    queryLanguage: QueryLanguage.SQL,
    driverPackage: "snowflake-sdk",
    description: "Cloud data platform",
    fields: [
      { key: "account", label: "Account", type: ConnectionFieldType.TEXT, required: true, placeholder: "xyz12345", group: "Connection" },
      { key: "username", label: "Username", type: ConnectionFieldType.TEXT, required: true, group: "Authentication" },
      { key: "password", label: "Password", type: ConnectionFieldType.PASSWORD, sensitive: true, group: "Authentication" },
      { key: "warehouse", label: "Warehouse", type: ConnectionFieldType.TEXT, group: "Connection" },
      { key: "database", label: "Database", type: ConnectionFieldType.TEXT, group: "Connection" },
      { key: "schema", label: "Schema", type: ConnectionFieldType.TEXT, group: "Connection" },
      { key: "role", label: "Role", type: ConnectionFieldType.TEXT, group: "Authentication" },
      ...commonAdvanced,
    ],
  },
  {
    id: "trino",
    name: "Trino",
    category: DatabaseCategory.DATA_WAREHOUSE,
    connectionMethod: ConnectionMethod.NATIVE,
    queryLanguage: QueryLanguage.SQL,
    driverPackage: "trino-client",
    description: "Distributed SQL query engine",
    defaultPort: 8080,
    fields: [hostField, { ...portField, defaultValue: 8080 }, databaseField, usernameField, passwordField, sslField, connectionStringField, ...commonAdvanced],
  },

  // ==================== CLOUD DATABASES ====================
  {
    id: "azure-sql",
    name: "Azure SQL",
    category: DatabaseCategory.CLOUD,
    connectionMethod: ConnectionMethod.NATIVE,
    queryLanguage: QueryLanguage.SQL,
    driverPackage: "mssql",
    description: "Microsoft Azure SQL database",
    defaultPort: 1433,
    fields: [hostField, { ...portField, defaultValue: 1433 }, databaseField, usernameField, passwordField, sslField, connectionStringField, ...commonAdvanced],
  },
  {
    id: "azure-synapse",
    name: "Azure Synapse",
    category: DatabaseCategory.CLOUD,
    connectionMethod: ConnectionMethod.NATIVE,
    queryLanguage: QueryLanguage.SQL,
    driverPackage: "mssql",
    description: "Azure analytics service",
    defaultPort: 1433,
    fields: [hostField, { ...portField, defaultValue: 1433 }, databaseField, usernameField, passwordField, sslField, connectionStringField, ...commonAdvanced],
  },
  {
    id: "bunny-database",
    name: "Bunny Database",
    category: DatabaseCategory.CLOUD,
    connectionMethod: ConnectionMethod.HTTP,
    queryLanguage: QueryLanguage.SQL,
    driverPackage: "mysql2",
    description: "Managed MySQL by Bunny.net",
    defaultPort: 3306,
    fields: [hostField, { ...portField, defaultValue: 3306 }, databaseField, usernameField, passwordField, sslField, connectionStringField],
  },
  {
    id: "cloudflare-d1",
    name: "Cloudflare D1",
    category: DatabaseCategory.CLOUD,
    connectionMethod: ConnectionMethod.HTTP,
    queryLanguage: QueryLanguage.SQL,
    driverPackage: "@cloudflare/workers-types",
    description: "Cloudflare serverless SQLite",
    fields: [
      { key: "accountId", label: "Account ID", type: ConnectionFieldType.TEXT, required: true, group: "Connection" },
      { key: "databaseId", label: "Database ID", type: ConnectionFieldType.TEXT, required: true, group: "Connection" },
      tokenField,
      ...commonAdvanced,
    ],
  },
  {
    id: "cockroachdb",
    name: "CockroachDB",
    category: DatabaseCategory.CLOUD,
    connectionMethod: ConnectionMethod.NATIVE,
    queryLanguage: QueryLanguage.SQL,
    driverPackage: "pg",
    description: "Distributed PostgreSQL-compatible database",
    defaultPort: 26257,
    fields: [hostField, { ...portField, defaultValue: 26257 }, databaseField, usernameField, passwordField, sslField, connectionStringField, ...commonAdvanced],
  },
  {
    id: "google-spanner",
    name: "Google Spanner",
    category: DatabaseCategory.CLOUD,
    connectionMethod: ConnectionMethod.NATIVE,
    queryLanguage: QueryLanguage.SQL,
    driverPackage: "@google-cloud/spanner",
    description: "Google globally distributed database",
    preview: true,
    fields: [
      { key: "projectId", label: "Project ID", type: ConnectionFieldType.TEXT, required: true, group: "Connection" },
      { key: "instanceId", label: "Instance ID", type: ConnectionFieldType.TEXT, required: true, group: "Connection" },
      { key: "database", label: "Database", type: ConnectionFieldType.TEXT, required: true, group: "Connection" },
      { key: "serviceAccountJson", label: "Service Account JSON", type: ConnectionFieldType.JSON, group: "Authentication" },
      ...commonAdvanced,
    ],
  },
  {
    id: "motherduck",
    name: "MotherDuck",
    category: DatabaseCategory.CLOUD,
    connectionMethod: ConnectionMethod.HTTP,
    queryLanguage: QueryLanguage.SQL,
    driverPackage: "@motherduck/duckdb-wasm-client",
    description: "Serverless DuckDB in the cloud",
    fields: [tokenField, { key: "database", label: "Database", type: ConnectionFieldType.TEXT, group: "Connection" }, ...commonAdvanced],
  },
  {
    id: "singlestore",
    name: "SingleStore",
    category: DatabaseCategory.CLOUD,
    connectionMethod: ConnectionMethod.NATIVE,
    queryLanguage: QueryLanguage.SQL,
    driverPackage: "mysql2",
    description: "Distributed SQL database",
    defaultPort: 3306,
    fields: [hostField, { ...portField, defaultValue: 3306 }, databaseField, usernameField, passwordField, sslField, connectionStringField],
  },
  {
    id: "timescale",
    name: "Timescale",
    category: DatabaseCategory.CLOUD,
    connectionMethod: ConnectionMethod.NATIVE,
    queryLanguage: QueryLanguage.SQL,
    driverPackage: "pg",
    description: "Time-series database on PostgreSQL",
    defaultPort: 5432,
    fields: [hostField, { ...portField, defaultValue: 5432 }, databaseField, usernameField, passwordField, sslField, connectionStringField, ...commonAdvanced],
  },
  {
    id: "yugabytedb",
    name: "YugabyteDB",
    category: DatabaseCategory.CLOUD,
    connectionMethod: ConnectionMethod.NATIVE,
    queryLanguage: QueryLanguage.SQL,
    driverPackage: "pg",
    description: "Distributed PostgreSQL-compatible database",
    defaultPort: 5433,
    fields: [hostField, { ...portField, defaultValue: 5433 }, databaseField, usernameField, passwordField, sslField, connectionStringField, ...commonAdvanced],
  },

  // ==================== LAKEHOUSES ====================
  {
    id: "cloudflare-r2-sql",
    name: "Cloudflare R2 SQL",
    category: DatabaseCategory.LAKEHOUSE,
    connectionMethod: ConnectionMethod.HTTP,
    queryLanguage: QueryLanguage.SQL,
    driverPackage: "@cloudflare/workers-types",
    description: "SQL query over R2 storage",
    preview: true,
    fields: [accessKeyField, secretKeyField, { key: "accountId", label: "Account ID", type: ConnectionFieldType.TEXT, group: "Connection" }, ...commonAdvanced],
  },
  {
    id: "duklake",
    name: "DuckLake",
    category: DatabaseCategory.LAKEHOUSE,
    connectionMethod: ConnectionMethod.NATIVE,
    queryLanguage: QueryLanguage.SQL,
    driverPackage: "duckdb",
    description: "DuckDB over object storage",
    fields: [{ key: "filePath", label: "Database File", type: ConnectionFieldType.FILE, group: "Connection" }, accessKeyField, secretKeyField, ...commonAdvanced],
  },
  {
    id: "iceberg",
    name: "Iceberg",
    category: DatabaseCategory.LAKEHOUSE,
    connectionMethod: ConnectionMethod.NATIVE,
    queryLanguage: QueryLanguage.SQL,
    driverPackage: "@iceberg/core",
    description: "Open table format for data lakes",
    fields: [
      { key: "catalogUri", label: "Catalog URI", type: ConnectionFieldType.URL, required: true, group: "Connection" },
      { key: "warehouse", label: "Warehouse", type: ConnectionFieldType.TEXT, group: "Connection" },
      accessKeyField,
      secretKeyField,
      ...commonAdvanced,
    ],
  },

  // ==================== APPLICATION DATABASES ====================
  {
    id: "cube",
    name: "Cube",
    category: DatabaseCategory.APPLICATION,
    connectionMethod: ConnectionMethod.HTTP,
    queryLanguage: QueryLanguage.REST,
    driverPackage: "@cubejs-client/core",
    description: "Headless BI analytics",
    preview: true,
    fields: [{ key: "apiUrl", label: "API URL", type: ConnectionFieldType.URL, required: true, group: "Connection" }, tokenField, ...commonAdvanced],
  },
  {
    id: "dataverse",
    name: "Dataverse",
    category: DatabaseCategory.APPLICATION,
    connectionMethod: ConnectionMethod.HTTP,
    queryLanguage: QueryLanguage.REST,
    driverPackage: "@microsoft/powerplatform-dataverse",
    description: "Microsoft low-code data platform",
    fields: [
      { key: "environmentUrl", label: "Environment URL", type: ConnectionFieldType.URL, required: true, group: "Connection" },
      { key: "clientId", label: "Client ID", type: ConnectionFieldType.TEXT, group: "Authentication" },
      { key: "clientSecret", label: "Client Secret", type: ConnectionFieldType.PASSWORD, sensitive: true, group: "Authentication" },
      { key: "tenantId", label: "Tenant ID", type: ConnectionFieldType.TEXT, group: "Authentication" },
      ...commonAdvanced,
    ],
  },
  {
    id: "posthog",
    name: "PostHog",
    category: DatabaseCategory.APPLICATION,
    connectionMethod: ConnectionMethod.HTTP,
    queryLanguage: QueryLanguage.REST,
    driverPackage: "posthog-node",
    description: "Product analytics platform",
    fields: [{ key: "host", label: "Host", type: ConnectionFieldType.TEXT, placeholder: "https://app.posthog.com", group: "Connection" }, tokenField, ...commonAdvanced],
  },
  {
    id: "powerbi-semantic",
    name: "Power BI Semantic Models",
    category: DatabaseCategory.APPLICATION,
    connectionMethod: ConnectionMethod.HTTP,
    queryLanguage: QueryLanguage.REST,
    driverPackage: "@azure/identity",
    description: "Power BI datasets and reports",
    preview: true,
    fields: [
      { key: "workspaceId", label: "Workspace ID", type: ConnectionFieldType.TEXT, group: "Connection" },
      { key: "clientId", label: "Client ID", type: ConnectionFieldType.TEXT, group: "Authentication" },
      { key: "clientSecret", label: "Client Secret", type: ConnectionFieldType.PASSWORD, sensitive: true, group: "Authentication" },
      { key: "tenantId", label: "Tenant ID", type: ConnectionFieldType.TEXT, group: "Authentication" },
    ],
  },
  {
    id: "salesforce",
    name: "Salesforce",
    category: DatabaseCategory.APPLICATION,
    connectionMethod: ConnectionMethod.HTTP,
    queryLanguage: QueryLanguage.REST,
    driverPackage: "jsforce",
    description: "CRM platform with SOQL",
    fields: [
      { key: "instanceUrl", label: "Instance URL", type: ConnectionFieldType.URL, placeholder: "https://your-org.salesforce.com", group: "Connection" },
      { key: "clientId", label: "Client ID", type: ConnectionFieldType.TEXT, group: "Authentication" },
      { key: "clientSecret", label: "Client Secret", type: ConnectionFieldType.PASSWORD, sensitive: true, group: "Authentication" },
      usernameField,
      passwordField,
      ...commonAdvanced,
    ],
  },
  {
    id: "stripe",
    name: "Stripe",
    category: DatabaseCategory.APPLICATION,
    connectionMethod: ConnectionMethod.HTTP,
    queryLanguage: QueryLanguage.REST,
    driverPackage: "stripe",
    description: "Payment processing platform",
    preview: true,
    fields: [
      { key: "secretKey", label: "Secret Key", type: ConnectionFieldType.PASSWORD, sensitive: true, required: true, group: "Authentication", helpText: "sk_live_... or sk_test_..." },
      ...commonAdvanced,
    ],
  },

  // ==================== FILE FORMATS ====================
  {
    id: "avro",
    name: "Avro",
    category: DatabaseCategory.FILE_FORMAT,
    connectionMethod: ConnectionMethod.NATIVE,
    queryLanguage: QueryLanguage.SQL,
    driverPackage: "avro-js",
    description: "Avro data file format",
    fields: [
      { key: "filePath", label: "Avro File", type: ConnectionFieldType.FILE, required: true, group: "Connection" },
      { key: "schemaFile", label: "Schema File", type: ConnectionFieldType.FILE, group: "Connection" },
    ],
  },
  {
    id: "csv",
    name: "CSV",
    category: DatabaseCategory.FILE_FORMAT,
    connectionMethod: ConnectionMethod.NATIVE,
    queryLanguage: QueryLanguage.SQL,
    driverPackage: "csv-parse",
    description: "Comma-separated values files",
    fields: [
      { key: "filePath", label: "CSV File", type: ConnectionFieldType.FILE, required: true, group: "Connection" },
      { key: "delimiter", label: "Delimiter", type: ConnectionFieldType.TEXT, defaultValue: ",", group: "Connection" },
      { key: "hasHeader", label: "Header Row", type: ConnectionFieldType.CHECKBOX, defaultValue: true, group: "Connection" },
    ],
  },
  {
    id: "excel",
    name: "Excel",
    category: DatabaseCategory.FILE_FORMAT,
    connectionMethod: ConnectionMethod.NATIVE,
    queryLanguage: QueryLanguage.SQL,
    driverPackage: "exceljs",
    description: "Microsoft Excel files",
    fields: [
      { key: "filePath", label: "Excel File", type: ConnectionFieldType.FILE, required: true, group: "Connection" },
      { key: "sheet", label: "Worksheet", type: ConnectionFieldType.TEXT, group: "Connection", helpText: "Leave empty to browse all sheets" },
    ],
  },
  {
    id: "parquet",
    name: "Parquet",
    category: DatabaseCategory.FILE_FORMAT,
    connectionMethod: ConnectionMethod.NATIVE,
    queryLanguage: QueryLanguage.SQL,
    driverPackage: "parquetjs",
    description: "Parquet columnar file format",
    fields: [{ key: "filePath", label: "Parquet File", type: ConnectionFieldType.FILE, required: true, group: "Connection" }],
  },

  // ==================== STREAMING ====================
  {
    id: "risingwave",
    name: "RisingWave",
    category: DatabaseCategory.STREAMING,
    connectionMethod: ConnectionMethod.NATIVE,
    queryLanguage: QueryLanguage.SQL,
    driverPackage: "pg",
    description: "Streaming database",
    defaultPort: 4566,
    fields: [hostField, { ...portField, defaultValue: 4566 }, databaseField, usernameField, passwordField, sslField, connectionStringField, ...commonAdvanced],
  },

  // ==================== MESSAGE QUEUES ====================
  {
    id: "kafka",
    name: "Apache Kafka",
    category: DatabaseCategory.MESSAGE_QUEUE,
    connectionMethod: ConnectionMethod.NATIVE,
    queryLanguage: QueryLanguage.REST,
    driverPackage: "kafkajs",
    description: "Distributed event streaming platform",
    defaultPort: 9092,
    fields: [
      { key: "brokers", label: "Brokers", type: ConnectionFieldType.TEXT, required: true, placeholder: "localhost:9092,localhost:9093", group: "Connection", helpText: "Comma-separated list of broker addresses" },
      { key: "saslUsername", label: "SASL Username", type: ConnectionFieldType.TEXT, group: "Authentication" },
      { key: "saslPassword", label: "SASL Password", type: ConnectionFieldType.PASSWORD, sensitive: true, group: "Authentication" },
      sslField,
      ...commonAdvanced,
    ],
  },
  {
    id: "rabbitmq",
    name: "RabbitMQ",
    category: DatabaseCategory.MESSAGE_QUEUE,
    connectionMethod: ConnectionMethod.NATIVE,
    queryLanguage: QueryLanguage.REST,
    driverPackage: "amqplib",
    description: "Message broker",
    defaultPort: 5672,
    preview: true,
    fields: [hostField, { ...portField, defaultValue: 5672 }, usernameField, passwordField, sslField, connectionStringField, ...commonAdvanced],
  },

  // ==================== GRAPH DATABASES ====================
  {
    id: "memgraph",
    name: "Memgraph",
    category: DatabaseCategory.GRAPH,
    connectionMethod: ConnectionMethod.NATIVE,
    queryLanguage: QueryLanguage.CYPHER,
    driverPackage: "neo4j-driver",
    description: "In-memory graph database",
    defaultPort: 7687,
    fields: [hostField, { ...portField, defaultValue: 7687 }, usernameField, passwordField, sslField, connectionStringField, ...commonAdvanced],
  },
  {
    id: "neo4j",
    name: "Neo4j",
    category: DatabaseCategory.GRAPH,
    connectionMethod: ConnectionMethod.NATIVE,
    queryLanguage: QueryLanguage.CYPHER,
    driverPackage: "neo4j-driver",
    description: "Most popular graph database",
    defaultPort: 7687,
    fields: [hostField, { ...portField, defaultValue: 7687 }, databaseField, usernameField, passwordField, sslField, connectionStringField, ...commonAdvanced],
  },

  // ==================== VECTOR DATABASES ====================
  {
    id: "chromadb",
    name: "ChromaDB",
    category: DatabaseCategory.VECTOR,
    connectionMethod: ConnectionMethod.HTTP,
    queryLanguage: QueryLanguage.REST,
    driverPackage: "chromadb",
    description: "Open-source vector database",
    defaultPort: 8000,
    preview: true,
    fields: [hostField, { ...portField, defaultValue: 8000 }, { key: "authToken", label: "Auth Token", type: ConnectionFieldType.PASSWORD, sensitive: true, group: "Authentication" }, ...commonAdvanced],
  },
  {
    id: "lancedb",
    name: "LanceDB",
    category: DatabaseCategory.VECTOR,
    connectionMethod: ConnectionMethod.NATIVE,
    queryLanguage: QueryLanguage.REST,
    driverPackage: "@lancedb/lancedb",
    description: "Embedding database",
    preview: true,
    fields: [{ key: "filePath", label: "Database Directory", type: ConnectionFieldType.FILE, group: "Connection" }, ...commonAdvanced],
  },
  {
    id: "milvus",
    name: "Milvus",
    category: DatabaseCategory.VECTOR,
    connectionMethod: ConnectionMethod.NATIVE,
    queryLanguage: QueryLanguage.REST,
    driverPackage: "@zilliz/milvus2-sdk-node",
    description: "Distributed vector database",
    defaultPort: 19530,
    preview: true,
    fields: [hostField, { ...portField, defaultValue: 19530 }, usernameField, passwordField, sslField, connectionStringField, ...commonAdvanced],
  },
  {
    id: "pinecone",
    name: "Pinecone",
    category: DatabaseCategory.VECTOR,
    connectionMethod: ConnectionMethod.HTTP,
    queryLanguage: QueryLanguage.REST,
    driverPackage: "@pinecone-database/pinecone",
    description: "Managed vector database",
    preview: true,
    fields: [
      { key: "apiKey", label: "API Key", type: ConnectionFieldType.PASSWORD, sensitive: true, required: true, group: "Authentication" },
      { key: "environment", label: "Environment", type: ConnectionFieldType.TEXT, placeholder: "us-west1-gcp", group: "Connection" },
      { key: "indexName", label: "Index Name", type: ConnectionFieldType.TEXT, group: "Connection" },
    ],
  },
  {
    id: "qdrant",
    name: "Qdrant",
    category: DatabaseCategory.VECTOR,
    connectionMethod: ConnectionMethod.HTTP,
    queryLanguage: QueryLanguage.REST,
    driverPackage: "@qdrant/js-client-rest",
    description: "Vector similarity search engine",
    defaultPort: 6333,
    preview: true,
    fields: [hostField, { ...portField, defaultValue: 6333 }, { key: "apiKey", label: "API Key", type: ConnectionFieldType.PASSWORD, sensitive: true, group: "Authentication" }, sslField, ...commonAdvanced],
  },
  {
    id: "weaviate",
    name: "Weaviate",
    category: DatabaseCategory.VECTOR,
    connectionMethod: ConnectionMethod.HTTP,
    queryLanguage: QueryLanguage.REST,
    driverPackage: "weaviate-ts-client",
    description: "Vector search database",
    defaultPort: 8080,
    preview: true,
    fields: [hostField, { ...portField, defaultValue: 8080 }, { key: "apiKey", label: "API Key", type: ConnectionFieldType.PASSWORD, sensitive: true, group: "Authentication" }, sslField, ...commonAdvanced],
  },

  // ==================== CLOUD PROVIDERS ====================
  {
    id: "aiven",
    name: "Aiven",
    category: DatabaseCategory.CLOUD_PROVIDER,
    connectionMethod: ConnectionMethod.HTTP,
    queryLanguage: QueryLanguage.REST,
    driverPackage: "aiven-client",
    description: "Managed cloud database provider",
    fields: [
      { key: "apiToken", label: "API Token", type: ConnectionFieldType.PASSWORD, sensitive: true, required: true, group: "Authentication" },
      { key: "project", label: "Project", type: ConnectionFieldType.TEXT, group: "Connection" },
    ],
  },
  {
    id: "azure",
    name: "Azure",
    category: DatabaseCategory.CLOUD_PROVIDER,
    connectionMethod: ConnectionMethod.HTTP,
    queryLanguage: QueryLanguage.REST,
    driverPackage: "@azure/identity",
    description: "Microsoft Azure cloud platform",
    fields: [
      { key: "tenantId", label: "Tenant ID", type: ConnectionFieldType.TEXT, group: "Authentication" },
      { key: "clientId", label: "Client ID", type: ConnectionFieldType.TEXT, group: "Authentication" },
      { key: "clientSecret", label: "Client Secret", type: ConnectionFieldType.PASSWORD, sensitive: true, group: "Authentication" },
      { key: "subscriptionId", label: "Subscription ID", type: ConnectionFieldType.TEXT, group: "Connection" },
    ],
  },
  {
    id: "cloudflare",
    name: "Cloudflare",
    category: DatabaseCategory.CLOUD_PROVIDER,
    connectionMethod: ConnectionMethod.HTTP,
    queryLanguage: QueryLanguage.REST,
    driverPackage: "@cloudflare/workers-types",
    description: "Cloudflare edge network platform",
    fields: [
      { key: "apiToken", label: "API Token", type: ConnectionFieldType.PASSWORD, sensitive: true, required: true, group: "Authentication" },
      { key: "accountId", label: "Account ID", type: ConnectionFieldType.TEXT, group: "Connection" },
    ],
  },
  {
    id: "digital-ocean",
    name: "Digital Ocean",
    category: DatabaseCategory.CLOUD_PROVIDER,
    connectionMethod: ConnectionMethod.HTTP,
    queryLanguage: QueryLanguage.REST,
    driverPackage: "do-wrapper",
    description: "Cloud infrastructure provider",
    fields: [
      { key: "apiToken", label: "API Token", type: ConnectionFieldType.PASSWORD, sensitive: true, required: true, group: "Authentication" },
    ],
  },
  {
    id: "neon",
    name: "Neon",
    category: DatabaseCategory.CLOUD_PROVIDER,
    connectionMethod: ConnectionMethod.HTTP,
    queryLanguage: QueryLanguage.SQL,
    driverPackage: "@neondatabase/serverless",
    description: "Serverless PostgreSQL",
    fields: [
      { key: "apiKey", label: "API Key", type: ConnectionFieldType.PASSWORD, sensitive: true, group: "Authentication" },
      { key: "projectId", label: "Project ID", type: ConnectionFieldType.TEXT, group: "Connection" },
      { key: "databaseUrl", label: "Database URL", type: ConnectionFieldType.URL, placeholder: "postgresql://user:pass@ep-xxx.aws.neon.tech/db", group: "Connection" },
    ],
  },
  {
    id: "supabase",
    name: "Supabase",
    category: DatabaseCategory.CLOUD_PROVIDER,
    connectionMethod: ConnectionMethod.HTTP,
    queryLanguage: QueryLanguage.SQL,
    driverPackage: "@supabase/supabase-js",
    description: "Open-source Firebase alternative",
    fields: [
      { key: "projectUrl", label: "Project URL", type: ConnectionFieldType.URL, required: true, placeholder: "https://xyz.supabase.co", group: "Connection" },
      { key: "anonKey", label: "Anon Key", type: ConnectionFieldType.PASSWORD, sensitive: true, group: "Authentication" },
      { key: "serviceRoleKey", label: "Service Role Key", type: ConnectionFieldType.PASSWORD, sensitive: true, group: "Authentication" },
      { key: "databaseUrl", label: "Database URL", type: ConnectionFieldType.URL, placeholder: "postgresql://postgres:pass@db.xyz.supabase.co:5432/postgres", group: "Connection" },
    ],
  },
  {
    id: "turso",
    name: "Turso",
    category: DatabaseCategory.CLOUD_PROVIDER,
    connectionMethod: ConnectionMethod.HTTP,
    queryLanguage: QueryLanguage.SQL,
    driverPackage: "@libsql/client",
    description: "SQLite for production",
    fields: [
      { key: "url", label: "Database URL", type: ConnectionFieldType.URL, required: true, placeholder: "libsql://your-db.turso.io", group: "Connection" },
      { key: "authToken", label: "Auth Token", type: ConnectionFieldType.PASSWORD, sensitive: true, group: "Authentication" },
    ],
  },
];